### ISSUE TITLE
Crux tide-index Error: FATAL: I/O error writing modifications

### ISSUE THREAD

**Issue by nattzy94** [crux-toolkit/crux-toolkit#544] opened 2021-12-19 04:11 UTC
Hi,

I ran `crux tide-index` using the following command: `../../crux-4.1.Linux.x86_64/bin/crux tide-index --output-dir orthoalltime --parameter-file crux.prm orthoalltime.fa orthoalltime`. However I run into an I/O error: `FATAL: I/O error writing modifications`. I have pasted the last few lines of the error log file below:

```
INFO: Wrote 61600000 peptides
INFO: Wrote 61700000 peptides
INFO: Wrote 61800000 peptides
INFO: Wrote 61900000 peptides
INFO: Wrote 62000000 peptides
INFO: Wrote 62100000 peptides
INFO: Wrote 62200000 peptides
INFO: Wrote 62300000 peptides
INFO: Wrote 62400000 peptides
INFO: Skipped 18361330 duplicate targets and 138326 duplicate decoys.
INFO: Wrote 31584994 targets and 30850765 decoys.
INFO: Computing modified peptides...
FATAL: I/O error writing modifications
```

I am using a slightly old version of Linux so this may be the problem. I've pasted the output of `lsb_release -a` here: 
```
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:	6.10
Codename:	Santiago
```

Is there a way around this error?

**Comment by bmx8177** [comment] 2021-12-19 15:13
Hi, can you upload your parameter file and fasta file so that we can replicate and debug the error? Thanks -Andy

**Comment by nattzy94** [comment] 2021-12-19 15:24
Sure, can I share with you via email?

**Comment by wsnoble** [comment] 2021-12-19 16:26
It looks like you ran out of disk space. Can you check?

**Comment by nattzy94** [comment] 2021-12-20 02:20
Yes, there is enough disk space. This is my disk usage:

 ```
===============================================================
|File System                   Usage (GB)          Limit (GB)	|
|e0470749                          10.51               50.00	|
|/scratch                          803.89            95367.43	|
 ===============================================================


/scratch inode usage: 2781
```

I am running in `/scratch`.  @wsnoble I have also shared the fasta and parameters file with you by email.

**Comment by kfattila** [comment] 2021-12-20 09:03
Hi, I think is an out-of-disk-space error. Note that, tide-index uses the temp folder to generate the modified peptides, it is determined by this parameter: 
`--temp-dir <string> – The name of the directory where temporary files will be created. If this parameter is blank, then the system temporary directory will be used Default = <empty>.
`
This is different from your output folder, or from your working folder. 

There is another important parameter, which might be useful for you to modify:
`
--max-mods <integer> – The maximum number of modifications that can be applied to a single peptide. Default = 255.
`

This is a pretty high value by default, you should try to use `--max-mod 2` or `--max-mod 3`

**Comment by nattzy94** [comment] 2021-12-20 15:00
@kfattila Thanks very much for the tip. Indeed, specifying the `--temp-dir` parameter worked and I managed to run `tide-index` successfully. I will also specify the `max-mods` parameter as suggested.

However, I have now run into another problem. When running `crux tide-search`, I run into a `FATAL: Unable to parse spectrum file` error. This is the last few lines of my job error report:

```
../../crux-4.1.Linux.x86_64/bin/crux tide-search --num-threads 1 --precursor-window 0.06 --parameter-file crux.prm --output-dir ACN-0340_m3_1.orthoalltime.tide-search --compute-sp T --score-function xcorr --pepxml-output T ../data/ACN/20211104_TY_Natheniel_0340_m3_1_ACN_FAIMS_OTIT_067ug.mgf orthoalltime
WARNING: Read parameter 'monoisotopic-precursor' from parameter file, but no such parameter exists.
WARNING: Read parameter 'use_sparse_matrix' from parameter file, but no such parameter exists.
INFO: Writing results to output directory 'ACN-0340_m3_1.orthoalltime.tide-search'.
INFO: CPU: std1614
INFO: Crux version: 4.1-e4b2f4d-2021-10-13
INFO: Mon Dec 20 08:43:38 Asia 2021
INFO: Beginning tide-search.
INFO: Running tide-search...
INFO: Number of Threads: 1
INFO: Reading index orthoalltime
INFO: Read 4767605 target proteins
INFO: Converting ../data/ACN/20211104_TY_Natheniel_0340_m3_1_ACN_FAIMS_OTIT_067ug.mgf to spectrumrecords format
INFO: Elapsed time starting conversion: 32.6 s
INFO: Converting ms_level 2 ...
DETAILED INFO: Support for vendor specific formats not enabled.
FATAL: Unable to parse spectrum file /scratch/users/nus/e0470749/NT030_unfrac/data/ACN/20211104_TY_Natheniel_0340_m3_1_ACN_FAIMS_OTIT_067ug.mgf. Error: locale::facet::_S_create_c_locale name not valid.
```

I can share the mgf file over dropbox if needed as it is quite large.

**Comment by kfattila** [comment] 2021-12-20 19:14
Hi, I have never seen such problems, maybe @wsnoble can suggest something. You also can try to convert your .mgf file to mzXML with MSConvert from ProteoWizard just to make sure other programs can parse your data. You may also share your data, I will try to take a look at it, if the options above don't work.

**Comment by wsnoble** [comment] 2021-12-20 20:18
I suspect that there is a malformed ID in the MGF file. I agree that trying to run msconvert on it is a good place to start. You can also try adding `--spectrum-parser mstoolkit` to your command line in case the problem is with pwiz.

**Comment by wsnoble** [comment] 2021-12-20 20:31
Also, to simplify debugging, try just running crux param-medic on this MGF file, without any other options.

**Comment by kfattila** [comment] 2021-12-24 13:20
I'm closing this issue since the tide-index part is fixed. If you still have a parsing problem please open a new issue for tide-search.

**Closed** 2021-12-24 13:20 UTC
